name: Rust RTI Test

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd rust/rti; cargo build --verbose

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        run: cd rust/rti; cargo test

  lf-rust-rti:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          # TODO: Change the below repo into 'lf-lang/lingua-franca'
          repository: chanijjani/lingua-franca
          submodules: true
          fetch-depth: 0          
          # TODO: Change the below ref 'master'
          ref: integration_tests_with_rust_rti
      - name: Prepare build environment
        # TODO: Change the below repo into 'lf-lang/lingua-franca@master'
        uses: chanijjani/lingua-franca/.github/actions/prepare-build-env@integration_tests_with_rust_rti 
      - name: Perform federated tests for C target with Rust RTI
        run:
          git clone https://github.com/hokeun/lf-rust-rti.git;
          cd lf-rust-rti;
          git checkout ${{ github.head_ref }};
          cd ../;
          ./gradlew targetTest -Ptarget=RustRti
