name: Rust RTI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd rust/rti; cargo build --verbose

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        run: cd rust/rti; cargo test

  # fetch-lf:
  #   uses: chanijjani/lingua-franca/.github/workflows/extract-ref.yml@master
  #   with:
  #     file: 'lingua-franca-ref.txt'

  lf-default:
    # needs: fetch-lf
    uses: chanijjani/lingua-franca/.github/workflows/c-tests-with-rust-rti.yml@integration_tests_with_rust_rti
